### ISSUE TITLE
NPC Requests 

### ISSUE THREAD

**Issue by hoshinocomet** [MaximiliumM/appearancemenumod#10]
Hi, a few more characters to consider for future versions. Thank you.

**Ripperdocs**
Fingers 
Cassius Ryder 
Charles Bucks 
Robert Rainwater 

**Cyberpsychos**
Lely Hein Goon
Ellis Carter
Diego Ramirez

**Cameos**
Roy Batty (Blade Runner)
Jesse Cox (Flaming Crotch Man)

**Others**
Mr. Blue Eyes
Certo Esquerdo 
Esquerdo Certo

**Comment by MaximiliumM** [comment]
Since it's in Discord already, I'll close the issue. Let's have requests in one place only ;)
