### ISSUE TITLE
[NPC Request] Lucius Rhyne, Deputy Mayor Holt and their bodyguard Lucas

### ISSUE THREAD

**Issue by MaximiliumM** [MaximiliumM/appearancemenumod#2]

**Comment by D4Z** [comment]
Added Donnie Carter, Jefferson Peralez, John Lucas, Daniel Lark and Mayor Lucius Rhyne. Still working on Deputy Mayor Holt.

**Comment by D4Z** [comment]
Deputy Mayor Holt.

**Comment by D4Z** [comment]
Added Mayor Lucius Rhyne, Deputy Mayor Weldon Holt and John Lucas as requested.
Added additional quest NPCs Jefferson Peralez, Donnie Carter and Daniel Lark.
