### ISSUE TITLE
NPC Request for companion and appearance

### ISSUE THREAD

**Issue by MrJordanL** [MaximiliumM/appearancemenumod#3]
Mayor Lucius Rhyne , Weldon Holt, Bodyguard lucas

Bonus request: Elon musk npc from start of corpo run and your corpo player's boss at the start of the game. 

I found lucius rhyne and holt and lucas in konpeki plaza secret room, rhyne tposes when attacked so idk if he has a combat state but when following he has a full set of walking/running animation, he runs like fat npc so could borrow melee attacks from the big tanky muscled npcs.  Holt also tposed when entering combat state, as followers with the other companion mod they also cowered in combat but you probably have predefined behaviour in your mod making it vastly superior.

**Comment by MaximiliumM** [comment]
Mayor Lucius Rhyne , Weldon Holt, Bodyguard Lucas already in.

I'll try to add the Elon Musk NPC and the boss you mentioned.
