### ISSUE TITLE
NPC behaviours request:

### ISSUE THREAD

**Issue by Silks1** [MaximiliumM/appearancemenumod#7]
I was wondering if it was possible for you to add configurable behaviours such as making the companion hostile towards you so can you fight them?

**Comment by MaximiliumM** [comment]
Most of the enemies, like Adam, if you spawn them without setting as companion, they'll fight you back :P 

But if you want to make Judy fight you, then that's a little bit more complicated. I haven't investigated it much, it's definitely doable, but it's not in the plans for now. Sorry.

We also want to have commands and animations, so we're definitely going to something like that in the future. But right now we're doing some backend work and focused on supporting the community by adding their requests until our database is sufficient.

**Comment by Silks1** [comment]
Oh how do i spawn them not as a companion?

**Comment by Silks1** [comment]
nvm i figured it out! thx :)
