### ISSUE TITLE
Kerry NPC Not Found

### ISSUE THREAD

**Issue by Nikademas** [MaximiliumM/appearancemenumod#8]
Hey Max,
Awesome Mod... I'm starting my 3rd run with Cyberpunk. I noticed that Kerry's NPC is listed as spawnable on Nexus, but I didn't find it on the drop down lists ingame.. Is he not available to spawn?

**Comment by MaximiliumM** [comment]
He's in Samurai category.

**Comment by Nikademas** [comment]
> He's in Samurai category.

And there he is!!...Even the younger version.. Man... UR the Best!!
